#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run arbitrary docker services. Run it like
# usual executable script:
#
# > ./run-docker-services.yml
#
# For configuration vars look at role variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: docker_services
  become: no
  become_user: root

  roles:
    - { role: sorrowless.docker_services, tags: ['docker_services'] }
